### ISSUE TITLE
About caffe missing include in openpose

### ISSUE THREAD

**Issue by zhengyuezhi** [makino-ryota/openpose_ros#1]
Hello, when running ./install_openpose_and_enable_package.sh, I found that the caffe in the 3rdparty of openpose is missing include. It is convenient to update it. Thank you, hard work.

**Comment by ryo-ponsan** [comment]
Sorry for replying late.
ahh...In my local repository, I have openpose in the openpose_ros, but I don't understand why there is nothing after cloning from my remote repository:(

You should cloned openpose from Github which Mr.stevenjj recommended.
In the openpose repository, you can install openpose and caffe by using ./install_caffe_and_openpose.sh
After that you can ./install_openpose_and_enable_package.sh.

Thank you for your advice.

**Comment by SilentLancer** [comment]
Hello @makino-ryota , I am still having issues with it. I did what you suggested but keeps having the same failure. Thank you

**Comment by ryo-ponsan** [comment]
@SilentLancer  Hello. Did you try these things?(https://github.com/stevenjj/openpose_ros/issues/18#issue-395538822)
If you have the error what I had, maybe you didn't install correct version of openpose and caffe(which is in the openpose).
